### PR TITLE
chore: update to `fresh@1.2.0`

### PR DESCRIPTION
**Pull request by iuioiua**
It's worth pushing this before #15 to catch any potential compatibility or performance issues.

### CODE REVIEW

**Comment by iuioiua** [comment]
Sidenote: how does this remote branch create deployments? I thought this wasn't possible.

**Comment by kt3k** [comment]
`examples/import_map.json` seems also referenced from `deno.json` at the root (and it's used by testing)

> Sidenote: how does this remote branch create deployments? I thought this wasn't possible.

Preview deployment for pull request is created only when the Deploy project doesn't have any env variable. (It doesn't seem documented though...)

**Comment by iuioiua** [comment]
> `examples/import_map.json` seems also referenced from `deno.json` at the root (and it's used by testing)

Fixed.

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by iuioiua** [comment]
Ah, thanks for fixing those mistakes! LOL

**Pull request merged**
